In [1]:
import numpy as np 

nx,ny=6,4
X = np.random.randint(0,5,size=(nx,ny))
X

array([[2, 3, 1, 0],
       [4, 3, 3, 4],
       [2, 0, 0, 1],
       [1, 3, 4, 2],
       [1, 4, 1, 2],
       [3, 1, 3, 0]])

In [2]:
X[:,slice(0,4,2)]

array([[2, 1],
       [4, 3],
       [2, 0],
       [1, 4],
       [1, 1],
       [3, 3]])

In [3]:
stripe = (slice(None),slice(0,4,2))

In [4]:
X[stripe]

array([[2, 1],
       [4, 3],
       [2, 0],
       [1, 4],
       [1, 1],
       [3, 3]])